apiVersion: v1
kind: Namespace
metadata:
  name: foxtrot
---
apiVersion: v1
kind: LimitRange
metadata:
  name: foxtrot-default-limits
  namespace: foxtrot
spec:
  limits:
    - type: Container
      default:
        cpu: "1"
        memory: 1Gi
      defaultRequest:
        cpu: 250m
        memory: 256Mi
